name: CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
            ls -la 
            git checkout ab84416
            make
