name: CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
            cat /etc/centos-release
            hostnamectl
            sudo yum install git
            git checkout 2.0.2
            make
