name: CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
            git checkout 2.0.2
            make
